package com.tripfuel.app;

import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;
import org.osmdroid.config.Configuration;
import org.osmdroid.tileprovider.tilesource.TileSourceFactory;
import org.osmdroid.util.GeoPoint;
import org.osmdroid.views.MapView;
import org.osmdroid.views.overlay.Marker;
import org.osmdroid.views.overlay.Polyline;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.xml.parsers.DocumentBuilderFactory;

public class TrailboundActivity extends Activity {
    private final int GREEN=Color.rgb(78,103,58), BROWN=Color.rgb(105,77,47), WHITE=Color.WHITE;
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private SharedPreferences prefs; private FrameLayout root; private LinearLayout page,nav; private MapView map;
    private EditText start,end,miles,gas,snacks,hotelCost,extras,year,make,model,mpg,odo,oil,nextOil,payload,hotelName,hotelAddress;
    private TextView result, vehicleSummary, hotelSummary;
    private final String BG_URL="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Route_66_through_the_Mojave_in_California.JPG/960px-Route_66_through_the_Mojave_in_California.JPG";

    @Override public void onCreate(Bundle b){super.onCreate(b);Configuration.getInstance().setUserAgentValue("TrailboundAndroid/3.0");prefs=getSharedPreferences("trailbound",MODE_PRIVATE);buildShell();loadRealBackground();showTrip();}

    private void buildShell(){root=new FrameLayout(this); root.setBackgroundColor(Color.rgb(30,31,25));
        ImageView bg=new ImageView(this); bg.setId(1001); bg.setScaleType(ImageView.ScaleType.CENTER_CROP); root.addView(bg,new FrameLayout.LayoutParams(-1,-1));
        View shade=new View(this); shade.setBackgroundColor(Color.argb(145,10,12,8)); root.addView(shade,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(12),dp(12),dp(12),dp(8));root.addView(shell,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView badge=t("66",17,true);badge.setGravity(Gravity.CENTER);badge.setTextColor(Color.rgb(110,45,33));badge.setBackground(round(Color.rgb(248,238,210),18,Color.rgb(110,45,33),3));top.addView(badge,new LinearLayout.LayoutParams(dp(58),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.setPadding(dp(10),0,0,0);titles.addView(t("TRAILBOUND",25,true));TextView sub=t("Road-trip planner",12,false);sub.setTextColor(Color.rgb(236,230,215));titles.addView(sub);top.addView(titles,new LinearLayout.LayoutParams(0,-2,1));shell.addView(top);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(0,dp(12),0,dp(18));sc.addView(page);shell.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setPadding(0,dp(6),0,0);shell.addView(nav);for(String x:new String[]{"TRIP","CAR","HOTEL","AREA"}){Button btt=navButton(x);nav.addView(btt,new LinearLayout.LayoutParams(0,dp(56),1));if(x.equals("TRIP"))btt.setOnClickListener(v->showTrip());if(x.equals("CAR"))btt.setOnClickListener(v->showCar());if(x.equals("HOTEL"))btt.setOnClickListener(v->showHotel());if(x.equals("AREA"))btt.setOnClickListener(v->showArea());}
        setContentView(root);}

    private void loadRealBackground(){io.execute(()->{try(InputStream in=new URL(BG_URL).openStream()){Bitmap bm=BitmapFactory.decodeStream(in);runOnUiThread(()->((ImageView)findViewById(1001)).setImageBitmap(bm));}catch(Exception ignored){}});}

    private void showTrip(){clear("TRIP");LinearLayout hero=card();hero.addView(h("Plan your adventure"));hero.addView(note("Route, fuel, lodging and your total vacation budget in one place."));start=field(hero,"START",prefs.getString("start",""),false);end=field(hero,"DESTINATION",prefs.getString("end",""),false);Button route=primary("MAP ROUTE + CALCULATE");hero.addView(route,blp());route.setOnClickListener(v->routeTrip());page.addView(hero);
        map=makeMap();page.addView(map,new LinearLayout.LayoutParams(-1,dp(260)));
        LinearLayout budget=card();budget.addView(h("Trip budget"));miles=field(budget,"ONE-WAY MILES",prefs.getString("miles",""),true);gas=field(budget,"AVG GAS $ / GAL",prefs.getString("gas","3.25"),true);snacks=field(budget,"SNACKS & DRINKS",prefs.getString("snacks","40"),true);hotelCost=field(budget,"HOTEL TOTAL",prefs.getString("hotelCost","160"),true);extras=field(budget,"OTHER TRIP MONEY",prefs.getString("extras","25"),true);Button calc=secondary("CALCULATE CURRENT NUMBERS");budget.addView(calc,blp());calc.setOnClickListener(v->calculate());result=info("Your estimate will appear here.");budget.addView(result);page.addView(budget);
        LinearLayout stops=card();stops.addView(h("Stops along your route"));stops.addView(note("Search around the mapped route for useful or fun stops."));for(String q:new String[]{"Food","Fuel","Parks","Attractions","Rest areas"}){Button b=secondary(q.toUpperCase(Locale.US));stops.addView(b,blp());b.setOnClickListener(v->findRouteStops(q));}page.addView(stops);
        LinearLayout save=card();save.addView(h("Planned vacations"));Button sv=primary("SAVE CURRENT VACATION");save.addView(sv,blp());sv.setOnClickListener(v->saveVacation());Button cl=secondary("CLEAR CURRENT PLANNER");save.addView(cl,blp());cl.setOnClickListener(v->clearCurrent());TextView list=info(savedVacationText());save.addView(list);page.addView(save);}

    private void showCar(){clear("CAR");LinearLayout c=card();c.addView(h("Your vehicle"));ImageView car=new ImageView(this);car.setScaleType(ImageView.ScaleType.CENTER_CROP);car.setBackground(round(Color.rgb(28,32,24),16,Color.rgb(112,123,87),1));c.addView(car,new LinearLayout.LayoutParams(-1,dp(170)));vehicleSummary=info("Add a vehicle to calculate maintenance and payload-adjusted fuel use.");c.addView(vehicleSummary);year=field(c,"YEAR",prefs.getString("year","2020"),true);make=field(c,"MAKE",prefs.getString("make","Toyota"),false);model=field(c,"MODEL",prefs.getString("model","Camry"),false);mpg=field(c,"EPA COMBINED MPG",prefs.getString("mpg","28"),true);odo=field(c,"CURRENT ODOMETER",prefs.getString("odo","50000"),true);oil=field(c,"CURRENT OIL LIFE %",prefs.getString("oil","60"),true);nextOil=field(c,"NEXT OIL CHANGE DUE AT",prefs.getString("nextOil","55000"),true);payload=field(c,"TRIP PAYLOAD (LB)",prefs.getString("payload","0"),true);Button auto=primary("GET VEHICLE MPG + PHOTO");c.addView(auto,blp());auto.setOnClickListener(v->{saveCar();lookupMpgAndPhoto(car);});Button sv=secondary("SAVE VEHICLE");c.addView(sv,blp());sv.setOnClickListener(v->{saveCar();updateCarSummary();toast("Vehicle saved");});page.addView(c);updateCarSummary();}

    private void showHotel(){clear("HOTEL");LinearLayout c=card();c.addView(h("Hotel base"));hotelName=field(c,"HOTEL NAME",prefs.getString("hotelName",""),false);hotelAddress=field(c,"HOTEL ADDRESS",prefs.getString("hotelAddress",""),false);hotelCost=field(c,"HOTEL TOTAL",prefs.getString("hotelCost","160"),true);Button save=primary("SAVE HOTEL TO CURRENT VACATION");c.addView(save,blp());save.setOnClickListener(v->{saveHotel();toast("Hotel saved");});page.addView(c);map=makeMap();page.addView(map,new LinearLayout.LayoutParams(-1,dp(260)));LinearLayout near=card();near.addView(h("Around your hotel"));hotelSummary=info("Map your hotel to explore the surrounding area.");near.addView(hotelSummary);Button emb=primary("MAP HOTEL + AREA");near.addView(emb,blp());emb.setOnClickListener(v->{saveHotel();mapHotel();});for(String q:new String[]{"Restaurants","Coffee","Groceries","Parks","Attractions","Fuel","Pharmacy"}){Button b=secondary(q.toUpperCase(Locale.US));near.addView(b,blp());b.setOnClickListener(v->findHotelPlaces(q));}page.addView(near);}

    private void showArea(){clear("AREA");LinearLayout c=card();c.addView(h("Trip & area intelligence"));c.addView(note("This is about the whole trip: distance, driving time, weather, hotel base, fuel needs, route context and useful places along the way."));result=info(summary());c.addView(result);Button u=primary("REFRESH LIVE AREA INFO");c.addView(u,blp());u.setOnClickListener(v->refreshArea());page.addView(c);}

    private void routeTrip(){saveTrip();if(start.getText().toString().trim().isEmpty()||end.getText().toString().trim().isEmpty()){toast("Enter start and destination");return;}result.setText("Mapping route…");io.execute(()->{try{double[] a=geocode(start.getText().toString()),b=geocode(end.getText().toString());JSONObject r=new JSONObject(get("https://router.project-osrm.org/route/v1/driving/"+a[1]+","+a[0]+";"+b[1]+","+b[0]+"?overview=full&geometries=geojson")).getJSONArray("routes").getJSONObject(0);double mi=r.getDouble("distance")/1609.344,hr=r.getDouble("duration")/3600;JSONArray coords=r.getJSONObject("geometry").getJSONArray("coordinates");prefs.edit().putString("miles",String.format(Locale.US,"%.1f",mi)).putFloat("duration",(float)hr).putString("routeGeo",coords.toString()).apply();runOnUiThread(()->{miles.setText(String.format(Locale.US,"%.1f",mi));drawRoute(a,b,coords);calculate();});}catch(Exception e){runOnUiThread(()->result.setText("Route lookup failed: "+e.getMessage()));}});}

    private void drawRoute(double[] a,double[] b,JSONArray coords){map.getOverlays().clear();List<GeoPoint> pts=new ArrayList<>();try{for(int i=0;i<coords.length();i++){JSONArray p=coords.getJSONArray(i);pts.add(new GeoPoint(p.getDouble(1),p.getDouble(0)));}}catch(Exception ignored){}Polyline line=new Polyline();line.setPoints(pts);line.setColor(Color.rgb(214,164,92));line.setWidth(8f);map.getOverlays().add(line);mark(map,new GeoPoint(a[0],a[1]),"Start");mark(map,new GeoPoint(b[0],b[1]),"Destination");if(!pts.isEmpty()){map.zoomToBoundingBox(line.getBounds(),true,80);}map.invalidate();}

    private void calculate(){saveTrip();double mi=n(prefs.getString("miles","0")),base=n(prefs.getString("mpg","28")),pay=n(prefs.getString("payload","0")),gp=n(prefs.getString("gas","3.25"));double adjusted=base*Math.max(.72,1-(pay/100.0)*.01);if(mi<=0||adjusted<=0||gp<=0){toast("Need miles, MPG and gas price");return;}double rt=mi*2,gals=rt/adjusted,fuel=gals*gp,total=fuel+n(prefs.getString("snacks","0"))+n(prefs.getString("hotelCost","0"))+n(prefs.getString("extras","0"));double hr=prefs.getFloat("duration",0);result.setText("ROUND TRIP  "+one(rt)+" mi\nDRIVE TIME  "+(hr>0?one(hr*2)+" hr":"route first")+"\nPAYLOAD-ADJUSTED MPG  "+one(adjusted)+"*\nFUEL NEEDED  "+one(gals)+" gal\nGAS COST  "+money(fuel)+"\n\nENTIRE TRIP  "+money(total)+"\n\n*Payload adjustment is an estimate, not an EPA rating.");}

    private void lookupMpgAndPhoto(ImageView iv){String y=prefs.getString("year",""),mk=prefs.getString("make",""),md=prefs.getString("model","");io.execute(()->{try{Document d=xml("https://www.fueleconomy.gov/ws/rest/vehicle/menu/options?year="+enc(y)+"&make="+enc(mk)+"&model="+enc(md));NodeList vals=d.getElementsByTagName("value");if(vals.getLength()==0)throw new Exception("No EPA match");Document vd=xml("https://www.fueleconomy.gov/ws/rest/vehicle/"+vals.item(0).getTextContent().trim());String found=vd.getElementsByTagName("comb08").item(0).getTextContent().trim();prefs.edit().putString("mpg",found).apply();String title=URLEncoder.encode(mk+" "+md,"UTF-8");JSONObject js=new JSONObject(get("https://en.wikipedia.org/api/rest_v1/page/summary/"+title));String src=js.optJSONObject("thumbnail")!=null?js.getJSONObject("thumbnail").optString("source",""):"";Bitmap bm=null;if(!src.isEmpty())try(InputStream in=new URL(src).openStream()){bm=BitmapFactory.decodeStream(in);}Bitmap finalBm=bm;runOnUiThread(()->{mpg.setText(found);if(finalBm!=null)iv.setImageBitmap(finalBm);updateCarSummary();});}catch(Exception e){runOnUiThread(()->toast("Vehicle lookup failed: "+e.getMessage()));}});}

    private void updateCarSummary(){if(vehicleSummary==null)return;double base=n(prefs.getString("mpg","28")),pay=n(prefs.getString("payload","0")),adj=base*Math.max(.72,1-(pay/100.0)*.01);double od=n(prefs.getString("odo","0")),due=n(prefs.getString("nextOil","0"));vehicleSummary.setText(prefs.getString("year","")+" "+prefs.getString("make","")+" "+prefs.getString("model","")+"\nEPA MPG: "+one(base)+" • Payload estimate: "+one(adj)+" MPG\nOdometer: "+String.format(Locale.US,"%,.0f",od)+" mi • Oil life: "+prefs.getString("oil","0")+"%\nOil change in about "+String.format(Locale.US,"%,.0f",Math.max(0,due-od))+" mi");}

    private void mapHotel(){String q=prefs.getString("hotelAddress","");if(q.isEmpty()){toast("Enter hotel address");return;}hotelSummary.setText("Mapping hotel…");io.execute(()->{try{double[] g=geocode(q);runOnUiThread(()->{map.getOverlays().clear();GeoPoint p=new GeoPoint(g[0],g[1]);mark(map,p,prefs.getString("hotelName","Hotel"));map.getController().setZoom(14);map.getController().setCenter(p);hotelSummary.setText(prefs.getString("hotelName","Hotel")+"\n"+q+"\nTap a category below to search nearby.");});}catch(Exception e){runOnUiThread(()->hotelSummary.setText("Hotel map failed: "+e.getMessage()));}});}

    private void findHotelPlaces(String cat){String q=prefs.getString("hotelAddress","");if(q.isEmpty()){toast("Save hotel first");return;}io.execute(()->{try{double[] g=geocode(q);String tag=overpassTag(cat);searchOverpass(g[0],g[1],tag,3500,cat);}catch(Exception e){runOnUiThread(()->toast("Search failed"));}});}
    private void findRouteStops(String cat){String geo=prefs.getString("routeGeo","");if(geo.isEmpty()){toast("Map a route first");return;}try{JSONArray arr=new JSONArray(geo);JSONArray mid=arr.getJSONArray(arr.length()/2);double lat=mid.getDouble(1),lon=mid.getDouble(0);io.execute(()->{try{searchOverpass(lat,lon,overpassTag(cat),12000,cat+" along route");}catch(Exception e){runOnUiThread(()->toast("Search failed"));}});}catch(Exception e){toast("Route data unavailable");}}
    private String overpassTag(String c){c=c.toLowerCase();if(c.contains("food")||c.contains("restaurant"))return "[amenity=restaurant]";if(c.contains("coffee"))return "[amenity=cafe]";if(c.contains("fuel"))return "[amenity=fuel]";if(c.contains("park"))return "[leisure=park]";if(c.contains("pharmacy"))return "[amenity=pharmacy]";if(c.contains("grocer"))return "[shop=supermarket]";if(c.contains("rest"))return "[highway=rest_area]";return "[tourism=attraction]";}
    private void searchOverpass(double lat,double lon,String tag,int radius,String label)throws Exception{String q="[out:json][timeout:20];nwr(around:"+radius+","+lat+","+lon+")"+tag+";out center tags 20;";JSONObject j=new JSONObject(post("https://overpass-api.de/api/interpreter","data="+enc(q)));JSONArray es=j.getJSONArray("elements");StringBuilder names=new StringBuilder(label.toUpperCase()+"\n");runOnUiThread(()->map.getOverlays().clear());int count=0;for(int i=0;i<es.length()&&count<12;i++){JSONObject o=es.getJSONObject(i),tags=o.optJSONObject("tags");if(tags==null)continue;String name=tags.optString("name","");if(name.isEmpty())continue;double la=o.has("lat")?o.optDouble("lat"):o.optJSONObject("center").optDouble("lat"),lo=o.has("lon")?o.optDouble("lon"):o.optJSONObject("center").optDouble("lon");names.append("• ").append(name).append("\n");count++;runOnUiThread(()->mark(map,new GeoPoint(la,lo),name));}String txt=names.toString();runOnUiThread(()->{if(hotelSummary!=null)hotelSummary.setText(txt);else if(result!=null)result.setText(txt);map.invalidate();});}

    private void refreshArea(){String dest=prefs.getString("end","");if(dest.isEmpty()){toast("Save a destination first");return;}result.setText("Refreshing area info…");io.execute(()->{try{double[] g=geocode(dest);JSONObject w=new JSONObject(get("https://api.open-meteo.com/v1/forecast?latitude="+g[0]+"&longitude="+g[1]+"&current=temperature_2m,apparent_temperature,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph")).getJSONObject("current");String s=summary()+"\n\nDESTINATION WEATHER NOW\n"+one(w.optDouble("temperature_2m"))+"°F • feels like "+one(w.optDouble("apparent_temperature"))+"°F\nWind "+one(w.optDouble("wind_speed_10m"))+" mph\n\nTRIP CONTEXT\nUse the route map for stops along the drive and the hotel map for your local base. The AREA tab combines both into one vacation overview.";runOnUiThread(()->result.setText(s));}catch(Exception e){runOnUiThread(()->result.setText(summary()+"\n\nLive update failed: "+e.getMessage()));}});}

    private String summary(){double mi=n(prefs.getString("miles","0")),base=n(prefs.getString("mpg","28")),pay=n(prefs.getString("payload","0")),adj=base*Math.max(.72,1-(pay/100.0)*.01),hr=prefs.getFloat("duration",0);return "TRIP\n"+prefs.getString("start","Start")+" → "+prefs.getString("end","Destination")+(mi>0?"\n"+one(mi)+" mi each way • "+one(mi*2)+" mi round trip":"")+(hr>0?"\nApprox. "+one(hr)+" hr each way":"")+"\n\nCAR\n"+prefs.getString("year","")+" "+prefs.getString("make","")+" "+prefs.getString("model","")+" • "+one(adj)+" estimated MPG with payload\n\nHOTEL\n"+prefs.getString("hotelName","No hotel saved")+(prefs.getString("hotelAddress","").isEmpty()?"":"\n"+prefs.getString("hotelAddress",""));}

    private void saveVacation(){saveTrip();saveHotel();saveCar();try{JSONArray arr=new JSONArray(prefs.getString("vacations","[]"));JSONObject o=new JSONObject();o.put("name",prefs.getString("end","Trip")+" vacation");o.put("start",prefs.getString("start",""));o.put("end",prefs.getString("end",""));o.put("hotel",prefs.getString("hotelName",""));o.put("hotelAddress",prefs.getString("hotelAddress",""));arr.put(o);prefs.edit().putString("vacations",arr.toString()).apply();toast("Vacation saved");}catch(Exception e){toast("Could not save trip");}}
    private String savedVacationText(){try{JSONArray a=new JSONArray(prefs.getString("vacations","[]"));if(a.length()==0)return "No saved vacations yet.";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);s.append("• ").append(o.optString("name","Vacation")).append("\n  ").append(o.optString("start")).append(" → ").append(o.optString("end")).append("\n");}return s.toString();}catch(Exception e){return "No saved vacations yet.";}}
    private void clearCurrent(){prefs.edit().remove("start").remove("end").remove("miles").remove("duration").remove("routeGeo").remove("hotelName").remove("hotelAddress").remove("hotelCost").remove("snacks").remove("extras").apply();showTrip();toast("Current planner cleared");}

    private void saveTrip(){if(start!=null)prefs.edit().putString("start",start.getText().toString()).putString("end",end.getText().toString()).putString("miles",miles==null?prefs.getString("miles",""):miles.getText().toString()).putString("gas",gas==null?prefs.getString("gas","3.25"):gas.getText().toString()).putString("snacks",snacks==null?prefs.getString("snacks","40"):snacks.getText().toString()).putString("hotelCost",hotelCost==null?prefs.getString("hotelCost","160"):hotelCost.getText().toString()).putString("extras",extras==null?prefs.getString("extras","25"):extras.getText().toString()).apply();}
    private void saveCar(){if(year!=null)prefs.edit().putString("year",year.getText().toString()).putString("make",make.getText().toString()).putString("model",model.getText().toString()).putString("mpg",mpg.getText().toString()).putString("odo",odo.getText().toString()).putString("oil",oil.getText().toString()).putString("nextOil",nextOil.getText().toString()).putString("payload",payload.getText().toString()).apply();}
    private void saveHotel(){if(hotelName!=null)prefs.edit().putString("hotelName",hotelName.getText().toString()).putString("hotelAddress",hotelAddress.getText().toString()).putString("hotelCost",hotelCost.getText().toString()).apply();}

    private void clear(String selected){page.removeAllViews();for(int i=0;i<nav.getChildCount();i++){Button b=(Button)nav.getChildAt(i);boolean on=b.getText().toString().equals(selected);b.setBackground(round(on?GREEN:Color.argb(235,25,27,22),16,on?Color.rgb(190,213,150):Color.rgb(102,108,82),1));}}
    private MapView makeMap(){MapView m=new MapView(this);m.setTileSource(TileSourceFactory.MAPNIK);m.setMultiTouchControls(true);m.getController().setZoom(5.5);m.getController().setCenter(new GeoPoint(36.5,-96));m.setBackground(round(Color.rgb(29,33,25),18,Color.rgb(105,112,84),1));return m;}
    private void mark(MapView m,GeoPoint p,String title){Marker mk=new Marker(m);mk.setPosition(p);mk.setAnchor(Marker.ANCHOR_CENTER,Marker.ANCHOR_BOTTOM);mk.setTitle(title);m.getOverlays().add(mk);}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(round(Color.argb(244,20,22,18),20,Color.rgb(112,118,90),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);c.setLayoutParams(p);return c;}
    private EditText field(LinearLayout c,String label,String val,boolean num){TextView l=t(label,12,true);l.setTextColor(Color.rgb(245,239,224));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);c.addView(l,lp);EditText e=new EditText(this);e.setText(val);e.setTextColor(WHITE);e.setHintTextColor(Color.rgb(195,191,180));e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackground(round(Color.rgb(12,14,11),14,Color.rgb(128,136,100),1));if(num)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(52));ep.topMargin=dp(5);c.addView(e,ep);return e;}
    private TextView h(String s){TextView t=t(s,20,true);t.setTextColor(Color.rgb(238,255,207));return t;} private TextView note(String s){TextView t=t(s,13,false);t.setTextColor(Color.rgb(236,231,216));t.setPadding(0,dp(4),0,dp(4));return t;} private TextView info(String s){TextView t=t(s,15,false);t.setLineSpacing(0,1.16f);t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackground(round(Color.rgb(11,13,10),14,Color.rgb(100,108,80),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(12);t.setLayoutParams(p);return t;}
    private Button primary(String s){Button b=button(s);b.setBackground(round(GREEN,14,Color.rgb(184,207,142),1));return b;}private Button secondary(String s){Button b=button(s);b.setBackground(round(BROWN,14,Color.rgb(174,139,99),1));return b;}private Button navButton(String s){Button b=button(s);b.setTextSize(11);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(56),1);p.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(p);return b;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return b;}private LinearLayout.LayoutParams blp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.topMargin=dp(12);return p;}
    private TextView t(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextColor(WHITE);t.setTextSize(size);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable round(int fill,int r,int stroke,int sw){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(sw),stroke);return g;}private int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private double n(String s){try{return Double.parseDouble(s.trim());}catch(Exception e){return 0;}}private String one(double d){return String.format(Locale.US,"%.1f",d);}private String money(double d){return NumberFormat.getCurrencyInstance(Locale.US).format(d);}private String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}
    private double[] geocode(String q)throws Exception{JSONArray a=new JSONArray(get("https://nominatim.openstreetmap.org/search?format=json&limit=1&q="+enc(q)));if(a.length()==0)throw new Exception("Place not found");JSONObject o=a.getJSONObject(0);return new double[]{o.getDouble("lat"),o.getDouble("lon")};}
    private String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(18000);c.setRequestProperty("User-Agent","TrailboundAndroid/3.0");try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()))){StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}finally{c.disconnect();}}
    private String post(String u,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded");c.getOutputStream().write(body.getBytes("UTF-8"));try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()))){StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}finally{c.disconnect();}}
    private Document xml(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestProperty("User-Agent","TrailboundAndroid/3.0");try{return DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(c.getInputStream());}finally{c.disconnect();}}
    @Override protected void onResume(){super.onResume();if(map!=null)map.onResume();}@Override protected void onPause(){if(map!=null)map.onPause();super.onPause();}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
